/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jps.l2app.server.ui;

import com.jps.l2app.entities.BetLimit;
import com.jps.l2app.entities.Employee;
import com.jps.l2app.entities.services.BetLimitService;
import com.jps.l2app.entities.services.EmployeeService;
import com.jps.l2app.main.Setup;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import com.jps.l2app.utils.UIUtilities;

/**
 *
 * @author admin
 */
public class BetLimitDiag extends javax.swing.JDialog {

    private final BetLimit limit;

    /**
     * Creates new form BetLimitDiag
     *
     * @param parent
     * @param limit
     */
    public BetLimitDiag(java.awt.Frame parent, BetLimit limit) {
        super(parent, true);
        initComponents();
        searchEmployees();
        this.limit = limit;
        updateGuiFields();

    }

    public static void createNewEmployee(java.awt.Frame parent) {
        BetLimitDiag diag = new BetLimitDiag(parent, new BetLimit());
        diag.setLocationRelativeTo(parent);
        diag.pack();
        diag.setVisible(true);
    }

    public static void edit(java.awt.Frame parent, BetLimit limit) {
        BetLimitDiag diag = new BetLimitDiag(parent, limit);
        diag.setLocationRelativeTo(parent);
        diag.pack();
        diag.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        drawCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        raffleCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        employeeCombo = new javax.swing.JComboBox();
        numField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        limitField = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        filter = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        drawCombo.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        drawCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3" }));

        jLabel1.setFont(new java.awt.Font(Setup.FONT_NAME, 1, 11)); // NOI18N
        jLabel1.setText("Draw:");

        raffleCombo.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        raffleCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL", "L2", "L3", "S3", "S2", "S3R", "P42", "P45", "P49", "P55", "4D" }));

        jLabel2.setFont(new java.awt.Font(Setup.FONT_NAME, 1, 11)); // NOI18N
        jLabel2.setText("Raffle:");

        jLabel3.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        jLabel3.setText("Zero: This limit is applied in all draws.");

        jLabel4.setFont(new java.awt.Font(Setup.FONT_NAME, 1, 11)); // NOI18N
        jLabel4.setText("Employee:");
        jLabel4.setEnabled(false);

        employeeCombo.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        employeeCombo.setEnabled(false);

        numField.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font(Setup.FONT_NAME, 1, 11)); // NOI18N
        jLabel5.setText("Number:");

        jLabel7.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        jLabel7.setText("<html><b>(1)</b> Single Num. Example: 03 <br><b>(2)</b> Wildcard. Example: 5_  <br><b>(3)</b> Range. Example: 33-45</html>");
        jLabel7.setToolTipText("This limit will apply to all numbers starting with 3.");

        jLabel8.setFont(new java.awt.Font(Setup.FONT_NAME, 1, 11)); // NOI18N
        jLabel8.setText("Priority By BET Number Types:");

        jLabel9.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        jLabel9.setText("Note: Negative limit value closes the number.");

        limitField.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N

        jLabel10.setFont(new java.awt.Font(Setup.FONT_NAME, 1, 11)); // NOI18N
        jLabel10.setText("Limit:");

        jButton1.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Gulim", 0, 21)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jps/l2app/server/ui/icons/limit.png"))); // NOI18N
        jLabel11.setText("Limit Details");

        filter.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        filter.setEnabled(false);

        jLabel13.setFont(new java.awt.Font(Setup.FONT_NAME, 1, 11)); // NOI18N
        jLabel13.setText("Filter:");
        jLabel13.setEnabled(false);

        jButton2.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        jButton2.setText("Search");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("<html>Limits are very dynamic.<br> You can create a limit suitable to your liking.</html>");

        jLabel12.setFont(new java.awt.Font(Setup.FONT_NAME, 1, 11)); // NOI18N
        jLabel12.setText("Type:");

        typeCombo.setFont(new java.awt.Font(Setup.FONT_NAME, 0, 11)); // NOI18N
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Limit shared by ALL Employees (LOW PRIORITY)", "PER EMPLOYEE Limit (MEDIUM PRIORITY)", "Limit SPECIFIC to an Employee (HIGH PRIORITY)" }));
        typeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(limitField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(drawCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(raffleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(16, 16, 16))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addGap(33, 33, 33)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton2))
                                                    .addComponent(employeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(drawCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(raffleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(employeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(limitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        searchEmployees();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void typeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboActionPerformed
        if (typeCombo.getSelectedIndex() == 2) {
            jLabel13.setEnabled(true);
            jLabel4.setEnabled(true);
            filter.setEnabled(true);
            jButton2.setEnabled(true);
            employeeCombo.setEnabled(true);
        } else {
            jLabel13.setEnabled(false);
            jLabel4.setEnabled(false);
            filter.setEnabled(false);
            jButton2.setEnabled(false);
            employeeCombo.setEnabled(false);
            employeeCombo.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_typeComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateEntityFields();
        BetLimitService.getInstance().update(limit);
        UIUtilities.addInfoMessage("Your changes are saved.");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox drawCombo;
    private javax.swing.JComboBox employeeCombo;
    private javax.swing.JTextField filter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner limitField;
    private javax.swing.JTextField numField;
    private javax.swing.JComboBox raffleCombo;
    private javax.swing.JComboBox typeCombo;
    // End of variables declaration//GEN-END:variables

    private void searchEmployees() {
        String text = filter.getText();
        List<Employee> search = EmployeeService.getInstance().search(text);
        DefaultComboBoxModel<Employee> m = new DefaultComboBoxModel(search.toArray(new Employee[]{}));
        employeeCombo.setModel(m);
    }

    private void updateGuiFields() {
        drawCombo.setSelectedIndex(limit.getDraw());
        raffleCombo.setSelectedItem(limit.getRaffleId());
        typeCombo.setSelectedIndex(limit.getLimitType());
        if (limit.getEmployee() != null) {
            employeeCombo.removeAllItems();
            employeeCombo.addItem(limit.getEmployee());
        }
        numField.setText(limit.getRaffleNumber());
        limitField.setValue(limit.getLimitValue());
    }

    private void updateEntityFields() {
        limit.setDraw(drawCombo.getSelectedIndex());
        limit.setRaffleId(raffleCombo.getSelectedItem().toString());
        limit.setLimitType(typeCombo.getSelectedIndex());
        if (employeeCombo.getSelectedItem() != null) {
            limit.setEmployee((Employee) employeeCombo.getSelectedItem());
        } else {
            limit.setEmployee(null);
        }
        limit.setRaffleNumber(numField.getText().trim());
        limit.setLimitValue(Double.parseDouble(limitField.getValue().toString()));
    }
}
